# Import all controllers automatically
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Individual route definitions
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

home:
    path: /
    controller: App\Controller\ForumController::index